services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: exam-flash-sales-system
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    container_name: redis
    image: redis:8-alpine
    restart: always
    ports:
      - 6379:6379

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  postgres_data:
