// This file is auto-generated by @hey-api/openapi-ts

export const ErrorResponseInputSchema = {
  type: 'object',
  properties: {
    message: {
      type: 'string',
    },
  },
} as const

export const NoContentResponseInputSchema = {} as const

export const ErrorResponseSchema = {
  type: 'object',
  properties: {
    message: {
      type: 'string',
    },
  },
  additionalProperties: false,
} as const

export const NoContentResponseSchema = {} as const
