// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import {
  getMyOrderByIdResponseTransformer,
  getMyOrdersResponseTransformer,
  getProductByIdResponseTransformer,
  getProductsResponseTransformer,
} from './transformers.gen'
import type {
  GetMyOrderByIdData,
  GetMyOrderByIdErrors,
  GetMyOrderByIdResponses,
  GetMyOrdersData,
  GetMyOrdersErrors,
  GetMyOrdersResponses,
  GetPaymentMethodsData,
  GetPaymentMethodsErrors,
  GetPaymentMethodsResponses,
  GetProductByIdData,
  GetProductByIdErrors,
  GetProductByIdResponses,
  GetProductsData,
  GetProductsErrors,
  GetProductsResponses,
  GetProductStockByIdData,
  GetProductStockByIdErrors,
  GetProductStockByIdResponses,
  RefreshTokenData,
  RefreshTokenErrors,
  RefreshTokenResponses,
  SignInConfirmData,
  SignInConfirmErrors,
  SignInConfirmResponses,
  SignInData,
  SignInErrors,
  SignInResponses,
  SignOutData,
  SignOutErrors,
  SignOutResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

export const signIn = <ThrowOnError extends boolean = false>(options: Options<SignInData, ThrowOnError>) =>
  (options.client ?? client).post<SignInResponses, SignInErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/auth/sign-in',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const signInConfirm = <ThrowOnError extends boolean = false>(
  options: Options<SignInConfirmData, ThrowOnError>,
) =>
  (options.client ?? client).post<SignInConfirmResponses, SignInConfirmErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/auth/sign-in/confirm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const signOut = <ThrowOnError extends boolean = false>(options?: Options<SignOutData, ThrowOnError>) =>
  (options?.client ?? client).post<SignOutResponses, SignOutErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/auth/sign-out',
    ...options,
  })

export const refreshToken = <ThrowOnError extends boolean = false>(options?: Options<RefreshTokenData, ThrowOnError>) =>
  (options?.client ?? client).post<RefreshTokenResponses, RefreshTokenErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/auth/refresh',
    ...options,
  })

export const getProducts = <ThrowOnError extends boolean = false>(options?: Options<GetProductsData, ThrowOnError>) =>
  (options?.client ?? client).get<GetProductsResponses, GetProductsErrors, ThrowOnError>({
    responseTransformer: getProductsResponseTransformer,
    responseType: 'json',
    url: '/api/products/',
    ...options,
  })

export const getProductById = <ThrowOnError extends boolean = false>(
  options: Options<GetProductByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetProductByIdResponses, GetProductByIdErrors, ThrowOnError>({
    responseTransformer: getProductByIdResponseTransformer,
    responseType: 'json',
    url: '/api/products/{productId}',
    ...options,
  })

export const getProductStockById = <ThrowOnError extends boolean = false>(
  options: Options<GetProductStockByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetProductStockByIdResponses, GetProductStockByIdErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/products/{productId}/stock',
    ...options,
  })

export const getMyOrders = <ThrowOnError extends boolean = false>(options?: Options<GetMyOrdersData, ThrowOnError>) =>
  (options?.client ?? client).get<GetMyOrdersResponses, GetMyOrdersErrors, ThrowOnError>({
    responseTransformer: getMyOrdersResponseTransformer,
    responseType: 'json',
    url: '/api/orders/my',
    ...options,
  })

export const getMyOrderById = <ThrowOnError extends boolean = false>(
  options: Options<GetMyOrderByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetMyOrderByIdResponses, GetMyOrderByIdErrors, ThrowOnError>({
    responseTransformer: getMyOrderByIdResponseTransformer,
    responseType: 'json',
    url: '/api/orders/my/{orderId}',
    ...options,
  })

export const getPaymentMethods = <ThrowOnError extends boolean = false>(
  options?: Options<GetPaymentMethodsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetPaymentMethodsResponses, GetPaymentMethodsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/payment-methods',
    ...options,
  })
