// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetMyOrderByIdResponse,
  GetMyOrdersResponse,
  GetProductByIdResponse,
  GetProductsResponse,
} from './types.gen'

export const getProductsResponseTransformer = async (data: any): Promise<GetProductsResponse> => {
  data = data.map((item: any) => {
    item.createdAt = new Date(item.createdAt)
    item.updatedAt = new Date(item.updatedAt)
    if (item.productStock) {
      item.productStock.createdAt = new Date(item.productStock.createdAt)
      item.productStock.updatedAt = new Date(item.productStock.updatedAt)
      if (item.productStock.product) {
        item.productStock.product.createdAt = new Date(item.productStock.product.createdAt)
        item.productStock.product.updatedAt = new Date(item.productStock.product.updatedAt)
      }
    }
    if (item.activePromos) {
      item.activePromos = item.activePromos.map((item: any) => {
        item.startDate = new Date(item.startDate)
        item.endDate = new Date(item.endDate)
        item.createdAt = new Date(item.createdAt)
        item.updatedAt = new Date(item.updatedAt)
        return item
      })
    }
    return item
  })
  return data
}

export const getProductByIdResponseTransformer = async (data: any): Promise<GetProductByIdResponse> => {
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.productStock) {
    data.productStock.createdAt = new Date(data.productStock.createdAt)
    data.productStock.updatedAt = new Date(data.productStock.updatedAt)
    if (data.productStock.product) {
      data.productStock.product.createdAt = new Date(data.productStock.product.createdAt)
      data.productStock.product.updatedAt = new Date(data.productStock.product.updatedAt)
    }
  }
  if (data.activePromos) {
    data.activePromos = data.activePromos.map((item: any) => {
      item.startDate = new Date(item.startDate)
      item.endDate = new Date(item.endDate)
      item.createdAt = new Date(item.createdAt)
      item.updatedAt = new Date(item.updatedAt)
      return item
    })
  }
  return data
}

export const getMyOrdersResponseTransformer = async (data: any): Promise<GetMyOrdersResponse> => {
  data = data.map((item: any) => {
    item.createdAt = new Date(item.createdAt)
    item.updatedAt = new Date(item.updatedAt)
    if (item.orderItems) {
      item.orderItems = item.orderItems.map((item: any) => {
        item.createdAt = new Date(item.createdAt)
        item.updatedAt = new Date(item.updatedAt)
        if (item.product) {
          item.product.createdAt = new Date(item.product.createdAt)
          item.product.updatedAt = new Date(item.product.updatedAt)
          if (item.product.productStock) {
            item.product.productStock.createdAt = new Date(item.product.productStock.createdAt)
            item.product.productStock.updatedAt = new Date(item.product.productStock.updatedAt)
            if (item.product.productStock.product) {
              item.product.productStock.product.createdAt = new Date(item.product.productStock.product.createdAt)
              item.product.productStock.product.updatedAt = new Date(item.product.productStock.product.updatedAt)
            }
          }
          if (item.product.activePromos) {
            item.product.activePromos = item.product.activePromos.map((item: any) => {
              item.startDate = new Date(item.startDate)
              item.endDate = new Date(item.endDate)
              item.createdAt = new Date(item.createdAt)
              item.updatedAt = new Date(item.updatedAt)
              return item
            })
          }
        }
        if (item.appliedPromo) {
          item.appliedPromo.startDate = new Date(item.appliedPromo.startDate)
          item.appliedPromo.endDate = new Date(item.appliedPromo.endDate)
          item.appliedPromo.createdAt = new Date(item.appliedPromo.createdAt)
          item.appliedPromo.updatedAt = new Date(item.appliedPromo.updatedAt)
        }
        return item
      })
    }
    return item
  })
  return data
}

export const getMyOrderByIdResponseTransformer = async (data: any): Promise<GetMyOrderByIdResponse> => {
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.orderItems) {
    data.orderItems = data.orderItems.map((item: any) => {
      item.createdAt = new Date(item.createdAt)
      item.updatedAt = new Date(item.updatedAt)
      if (item.product) {
        item.product.createdAt = new Date(item.product.createdAt)
        item.product.updatedAt = new Date(item.product.updatedAt)
        if (item.product.productStock) {
          item.product.productStock.createdAt = new Date(item.product.productStock.createdAt)
          item.product.productStock.updatedAt = new Date(item.product.productStock.updatedAt)
          if (item.product.productStock.product) {
            item.product.productStock.product.createdAt = new Date(item.product.productStock.product.createdAt)
            item.product.productStock.product.updatedAt = new Date(item.product.productStock.product.updatedAt)
          }
        }
        if (item.product.activePromos) {
          item.product.activePromos = item.product.activePromos.map((item: any) => {
            item.startDate = new Date(item.startDate)
            item.endDate = new Date(item.endDate)
            item.createdAt = new Date(item.createdAt)
            item.updatedAt = new Date(item.updatedAt)
            return item
          })
        }
      }
      if (item.appliedPromo) {
        item.appliedPromo.startDate = new Date(item.appliedPromo.startDate)
        item.appliedPromo.endDate = new Date(item.appliedPromo.endDate)
        item.appliedPromo.createdAt = new Date(item.appliedPromo.createdAt)
        item.appliedPromo.updatedAt = new Date(item.appliedPromo.updatedAt)
      }
      return item
    })
  }
  return data
}
