// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {})
}

export type ErrorResponseInput = {
  message?: string
}

export type NoContentResponseInput = unknown

export type ErrorResponse = {
  message?: string
}

export type NoContentResponse = unknown

export type SignInData = {
  body: {
    email: string
  }
  path?: never
  query?: never
  url: '/api/auth/sign-in'
}

export type SignInErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Unauthorized
   */
  401: ErrorResponse
  /**
   * Forbidden
   */
  403: ErrorResponse
  /**
   * Conflict
   */
  409: ErrorResponse
  /**
   * Internal Server Error
   */
  500: ErrorResponse
}

export type SignInError = SignInErrors[keyof SignInErrors]

export type SignInResponses = {
  /**
   * Default Response
   */
  200: {
    challengeId: string
  }
}

export type SignInResponse = SignInResponses[keyof SignInResponses]

export type SignInConfirmData = {
  body: {
    challengeId: string
    otp: string
  }
  path?: never
  query?: never
  url: '/api/auth/sign-in/confirm'
}

export type SignInConfirmErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Unauthorized
   */
  401: ErrorResponse
  /**
   * Forbidden
   */
  403: ErrorResponse
  /**
   * Conflict
   */
  409: ErrorResponse
  /**
   * Internal Server Error
   */
  500: ErrorResponse
}

export type SignInConfirmError = SignInConfirmErrors[keyof SignInConfirmErrors]

export type SignInConfirmResponses = {
  /**
   * Default Response
   */
  200: {
    token: string
    id: number
    email: string
  }
}

export type SignInConfirmResponse = SignInConfirmResponses[keyof SignInConfirmResponses]

export type SignOutData = {
  body?: never
  path?: never
  query?: never
  url: '/api/auth/sign-out'
}

export type SignOutErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Unauthorized
   */
  401: ErrorResponse
  /**
   * Forbidden
   */
  403: ErrorResponse
  /**
   * Conflict
   */
  409: ErrorResponse
  /**
   * Internal Server Error
   */
  500: ErrorResponse
}

export type SignOutError = SignOutErrors[keyof SignOutErrors]

export type SignOutResponses = {
  /**
   * Default Response
   */
  204: NoContentResponse
}

export type SignOutResponse = SignOutResponses[keyof SignOutResponses]

export type RefreshTokenData = {
  body?: never
  path?: never
  query?: never
  url: '/api/auth/refresh'
}

export type RefreshTokenErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Unauthorized
   */
  401: ErrorResponse
  /**
   * Forbidden
   */
  403: ErrorResponse
  /**
   * Conflict
   */
  409: ErrorResponse
  /**
   * Internal Server Error
   */
  500: ErrorResponse
}

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors]

export type RefreshTokenResponses = {
  /**
   * Default Response
   */
  200: {
    token: string
    id: number
    email: string
  }
}

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses]

export type GetProductsData = {
  body?: never
  path?: never
  query?: never
  url: '/api/products/'
}

export type GetProductsErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Unauthorized
   */
  401: ErrorResponse
  /**
   * Forbidden
   */
  403: ErrorResponse
  /**
   * Conflict
   */
  409: ErrorResponse
  /**
   * Internal Server Error
   */
  500: ErrorResponse
}

export type GetProductsError = GetProductsErrors[keyof GetProductsErrors]

export type GetProductsResponses = {
  /**
   * Default Response
   */
  200: Array<{
    id: number
    name: string
    description: string | null
    image: string | null
    priceInCents: number
    createdAt: Date
    updatedAt: Date
    productStock?: {
      productId: number
      warehouse: string
      availableQuantity: number
      reservedQuantity: number
      soldQuantity: number
      createdAt: Date
      updatedAt: Date
      product?: {
        id: number
        name: string
        description: string | null
        image: string | null
        priceInCents: number
        createdAt: Date
        updatedAt: Date
      } | null
    } | null
  }>
}

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses]

export type GetProductByIdData = {
  body?: never
  path: {
    productId: number
  }
  query?: never
  url: '/api/products/{productId}'
}

export type GetProductByIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Unauthorized
   */
  401: ErrorResponse
  /**
   * Forbidden
   */
  403: ErrorResponse
  /**
   * Conflict
   */
  409: ErrorResponse
  /**
   * Internal Server Error
   */
  500: ErrorResponse
}

export type GetProductByIdError = GetProductByIdErrors[keyof GetProductByIdErrors]

export type GetProductByIdResponses = {
  /**
   * Default Response
   */
  200: {
    id: number
    name: string
    description: string | null
    image: string | null
    priceInCents: number
    createdAt: Date
    updatedAt: Date
    productStock?: {
      productId: number
      warehouse: string
      availableQuantity: number
      reservedQuantity: number
      soldQuantity: number
      createdAt: Date
      updatedAt: Date
      product?: {
        id: number
        name: string
        description: string | null
        image: string | null
        priceInCents: number
        createdAt: Date
        updatedAt: Date
      } | null
    } | null
  }
}

export type GetProductByIdResponse = GetProductByIdResponses[keyof GetProductByIdResponses]

export type GetProductStockByIdData = {
  body?: never
  path: {
    productId: number
  }
  query?: never
  url: '/api/products/{productId}/stock'
}

export type GetProductStockByIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Unauthorized
   */
  401: ErrorResponse
  /**
   * Forbidden
   */
  403: ErrorResponse
  /**
   * Conflict
   */
  409: ErrorResponse
  /**
   * Internal Server Error
   */
  500: ErrorResponse
}

export type GetProductStockByIdError = GetProductStockByIdErrors[keyof GetProductStockByIdErrors]

export type GetProductStockByIdResponses = {
  /**
   * Default Response
   */
  200: number
}

export type GetProductStockByIdResponse = GetProductStockByIdResponses[keyof GetProductStockByIdResponses]

export type GetMyOrdersData = {
  body?: never
  path?: never
  query?: never
  url: '/api/orders/my'
}

export type GetMyOrdersErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Unauthorized
   */
  401: ErrorResponse
  /**
   * Forbidden
   */
  403: ErrorResponse
  /**
   * Conflict
   */
  409: ErrorResponse
  /**
   * Internal Server Error
   */
  500: ErrorResponse
}

export type GetMyOrdersError = GetMyOrdersErrors[keyof GetMyOrdersErrors]

export type GetMyOrdersResponses = {
  /**
   * Default Response
   */
  200: Array<{
    id: string
    userId: number
    status: 'pending' | 'submitted' | 'cancelled'
    note: string | null
    createdAt: Date
    updatedAt: Date
    orderItems?: Array<{
      id: number
      orderId: string
      productId: number
      quantity: number
      priceInCents: number
      discountPercentage: number
      appliedPromoId: number | null
      createdAt: Date
      updatedAt: Date
      product?: {
        id: number
        name: string
        description: string | null
        image: string | null
        priceInCents: number
        createdAt: Date
        updatedAt: Date
        productStock?: {
          productId: number
          warehouse: string
          availableQuantity: number
          reservedQuantity: number
          soldQuantity: number
          createdAt: Date
          updatedAt: Date
          product?: {
            id: number
            name: string
            description: string | null
            image: string | null
            priceInCents: number
            createdAt: Date
            updatedAt: Date
          } | null
        } | null
      } | null
      appliedPromo?: {
        id: number
        name: string
        description: string | null
        imageUrl: string | null
        discountPercentage: number
        status: 'upcoming' | 'active' | 'cancelled' | 'expired'
        startDate: Date
        endDate: Date
        productId: number
        createdAt: Date
        updatedAt: Date
      } | null
    }> | null
  }>
}

export type GetMyOrdersResponse = GetMyOrdersResponses[keyof GetMyOrdersResponses]

export type GetMyOrderByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/orders/my/{orderId}'
}

export type GetMyOrderByIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Unauthorized
   */
  401: ErrorResponse
  /**
   * Forbidden
   */
  403: ErrorResponse
  /**
   * Conflict
   */
  409: ErrorResponse
  /**
   * Internal Server Error
   */
  500: ErrorResponse
}

export type GetMyOrderByIdError = GetMyOrderByIdErrors[keyof GetMyOrderByIdErrors]

export type GetMyOrderByIdResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    userId: number
    status: 'pending' | 'submitted' | 'cancelled'
    note: string | null
    createdAt: Date
    updatedAt: Date
    orderItems?: Array<{
      id: number
      orderId: string
      productId: number
      quantity: number
      priceInCents: number
      discountPercentage: number
      appliedPromoId: number | null
      createdAt: Date
      updatedAt: Date
      product?: {
        id: number
        name: string
        description: string | null
        image: string | null
        priceInCents: number
        createdAt: Date
        updatedAt: Date
        productStock?: {
          productId: number
          warehouse: string
          availableQuantity: number
          reservedQuantity: number
          soldQuantity: number
          createdAt: Date
          updatedAt: Date
          product?: {
            id: number
            name: string
            description: string | null
            image: string | null
            priceInCents: number
            createdAt: Date
            updatedAt: Date
          } | null
        } | null
      } | null
      appliedPromo?: {
        id: number
        name: string
        description: string | null
        imageUrl: string | null
        discountPercentage: number
        status: 'upcoming' | 'active' | 'cancelled' | 'expired'
        startDate: Date
        endDate: Date
        productId: number
        createdAt: Date
        updatedAt: Date
      } | null
    }> | null
  }
}

export type GetMyOrderByIdResponse = GetMyOrderByIdResponses[keyof GetMyOrderByIdResponses]
